/*********************************************************************************
 *  SPDX-License-Identifier: LicenseRef-PolyForm-NC-1.0.0-NoAI
 *
 *  Licensed under PolyForm Noncommercial 1.0.0 + No AI Use Addendum v1.0.
 *  See: LICENSE and LICENSE-NO-AI.md in the project root for full terms.
 *
 *  Required Notice: Copyright 2025 Maxim Dokukin (https://maxdokukin.com)
 *  https://github.com/maxdokukin/XeWe-LED-OS
 *********************************************************************************/

// NOTE that the system MAX FPS depends on LED_STRIP_NUM_LEDS_MAX
// and as calculated as max_fps = 1000000 / (LED_STRIP_NUM_LEDS_MAX * 30)
// going over 1000 leds will drop fps too low (<30) for the effects to look good
// for more info, see: todo doc

#define LED_PIN_DATA                48
#define LED_PIN_CLOCK               12
#define LED_STRIP_NUM_LEDS_MAX      2000

// auto generated by the build chain
#define PROJECT_NAME "xewe-led-os"
#define BUILD_VERSION "2.3.8"
#define BUILD_TIMESTAMP "2026-09-13T17:58:34Z"
